### ISSUE TITLE
Allow loadModule to compile to esm

### ISSUE THREAD

**Issue by hayes** [milesj/boost#172]
Would be useful to be able to load a typescript module and have it downlevel to esm, and import with a dynamic import instead.  Not sure how complicated this would be to get working.

Use case is working with esm only libraries from a ts file/script.

Node allows using dynamic imports from CommonJS modules, but compiling ts with dynamic imports will replace those imports with require instead.

**Comment by milesj** [comment]
@hayes I'm not sure how we could do "and import with a dynamic import instead".

If it's a CJS file doing the require, then down-leveling to ESM is not possible for `requireModule`. We can maybe add a new `importModule` or something.

**Comment by milesj** [comment]
You'll need to use ESM loader hooks for this functionality. https://boostlib.dev/docs/module#ecmascript-module-loaders
